name: widgetbook_workspace
description: "Widget catalog for simple_flutter_template"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.18.0
  widgetbook_annotation: ^3.7.0
  simple_flutter_template:
    path: ../
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.18.0
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
